version: "3.8"
services:
  zookeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka1:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
    depends_on:
      - zookeper

  kafka2:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - 9093:9093
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9093"
    depends_on:
      - zookeper
